import type { Requester, Requisition } from "./types"

export type Role = "hod" | "ayp" | "nyp" | "finance"

export interface Account {
  role: Role
  name: string
  shortName: string
  initials: string
  email: string
  title: string
  scope: string
  phone: string
}

/**
 * Sign-in is passwordless, so the address *is* the identity — it decides
 * which side of the workflow you land on.
 */
export const DIRECTORY: Account[] = [
  {
    role: "hod",
    name: "Pastor David Adeyemi",
    shortName: "Pastor David",
    initials: "DA",
    email: "david.adeyemi@cwms.org",
    title: "Head of Department",
    scope: "Youth & Young Adults · Central Province",
    phone: "+234 803 412 7788",
  },
  {
    role: "ayp",
    name: "Pastor Grace Ojo",
    shortName: "Pastor Grace",
    initials: "GO",
    email: "grace.ojo@cwms.org",
    title: "Assistant National Youth Pastor",
    scope: "Youth & Young Adults · All Provinces",
    phone: "+234 802 771 3390",
  },
  {
    role: "nyp",
    name: "Pastor Emmanuel Bassey",
    shortName: "Pastor Emmanuel",
    initials: "EB",
    email: "emmanuel.bassey@cwms.org",
    title: "National Youth Pastor",
    scope: "Youth & Young Adults · National",
    phone: "+234 805 220 1147",
  },
  {
    role: "finance",
    name: "Mrs Ngozi Eze",
    shortName: "Mrs Ngozi",
    initials: "NE",
    email: "ngozi.eze@cwms.org",
    title: "Finance Officer",
    scope: "Finance · National Secretariat",
    phone: "+234 807 664 2210",
  },
]

export const FINANCE_USER = {
  name: "Mrs Ngozi Eze",
  shortName: "Mrs Ngozi",
  initials: "NE",
  role: "Finance Officer",
  roleShort: "FIN",
  email: "ngozi.eze@cwms.org",
  phone: "+234 807 664 2210",
  department: "Finance",
  unit: "National Secretariat",
  area: "National Secretariat, Abuja",
}

export const accountFor = (email: string) =>
  DIRECTORY.find((a) => a.email.toLowerCase() === email.trim().toLowerCase())

export const accountByRole = (role: Role) => DIRECTORY.find((a) => a.role === role) ?? DIRECTORY[0]

export const AYP_USER = {
  name: "Pastor Grace Ojo",
  shortName: "Pastor Grace",
  initials: "GO",
  role: "Assistant National Youth Pastor",
  roleShort: "ANYP",
  email: "grace.ojo@cwms.org",
  phone: "+234 802 771 3390",
  department: "Youth & Young Adults",
  unit: "All Provinces",
  area: "National Secretariat, Abuja",
  approver: "Pastor Emmanuel Bassey",
  approverRole: "National Youth Pastor",
}

export const NYP_USER = {
  name: "Pastor Emmanuel Bassey",
  shortName: "Pastor Emmanuel",
  initials: "EB",
  role: "National Youth Pastor",
  roleShort: "NYP",
  email: "emmanuel.bassey@cwms.org",
  phone: "+234 805 220 1147",
  department: "Youth & Young Adults",
  unit: "National",
  area: "National Secretariat, Abuja",
  recommender: "Pastor Grace Ojo",
  recommenderRole: "Assistant National Youth Pastor",
}

/** The HODs whose requisitions reach the ANYP. */
export const REQUESTERS: Record<string, Requester> = {
  david: {
    name: "Pastor David Adeyemi",
    initials: "DA",
    department: "Youth & Young Adults",
    unit: "Central Province",
  },
  ruth: {
    name: "Pastor Ruth Nwankwo",
    initials: "RN",
    department: "Youth & Young Adults",
    unit: "Lagos Province",
  },
  samuel: {
    name: "Pastor Samuel Okafor",
    initials: "SO",
    department: "Youth & Young Adults",
    unit: "Eastern Province",
  },
  halima: {
    name: "Pastor Halima Bello",
    initials: "HB",
    department: "Youth & Young Adults",
    unit: "Northern Province",
  },
}

export const CURRENT_USER = {
  name: "Pastor David Adeyemi",
  shortName: "Pastor David",
  role: "Head of Department",
  roleShort: "HOD",
  department: "Youth & Young Adults",
  unit: "Central Province",
  email: "david.adeyemi@cwms.org",
  phone: "+234 803 412 7788",
  area: "Abuja Area 3",
  parish: "Living Faith Chapel, Wuse II",
  memberSince: "2019-03-01",
  reviewer: "Pastor Grace Ojo",
  reviewerRole: "Assistant National Youth Pastor",
  approver: "Pastor Emmanuel Bassey",
  approverRole: "National Youth Pastor",
  initials: "DA",
}

export const SEED_REQUISITIONS: Requisition[] = [
  {
    id: "req-0847",
    reference: "REQ-2026-0847",
    programme: "Youth Convention 2026",
    programmeDate: "2026-11-15",
    location: "National Auditorium, Abuja",
    department: "Youth & Young Adults",
    purpose:
      "Annual youth leadership development convention for 1,200 delegates drawn from all twelve provinces. Covers venue, delegate transport and programme materials.",
    requester: REQUESTERS.david,
    items: [
      { id: "i1", description: "Venue rental & setup", amount: 60_000 },
      { id: "i2", description: "Graphics & publicity", amount: 20_000 },
      { id: "i3", description: "Transport & logistics", amount: 70_000 },
    ],
    attachments: [
      { id: "a1", name: "convention_proposal_v2.pdf", size: "1.2 MB", kind: "proposal" },
      { id: "a2", name: "venue_quotation_setup.pdf", size: "850 KB", kind: "quotation" },
    ],
    comments: [
      {
        id: "c1",
        author: "Pastor Grace Ojo",
        role: "Assistant National Youth Pastor",
        date: "2026-09-02",
        body: "Budget looks sound. Recommending to the National Youth Pastor for approval.",
      },
    ],
    activity: [
      { id: "e1", date: "2026-08-28", actor: "You", action: "Created requisition" },
      { id: "e2", date: "2026-08-29", actor: "You", action: "Submitted for review" },
      { id: "e3", date: "2026-09-02", actor: "Pastor Grace Ojo", action: "Recommended" },
    ],
    status: "awaiting_approval",
    stageDates: { submitted: "2026-08-29", recommended: "2026-09-02" },
    submittedAt: "2026-08-29",
    createdAt: "2026-08-28",
  },
  {
    id: "req-0839",
    reference: "REQ-2026-0839",
    programme: "Leadership Retreat",
    programmeDate: "2026-10-03",
    location: "Ilesa Retreat Centre, Osun",
    department: "Youth & Young Adults",
    purpose:
      "Three-day residential retreat for forty unit leaders, focused on discipleship and succession planning.",
    requester: REQUESTERS.david,
    items: [
      { id: "i1", description: "Accommodation (40 pax, 2 nights)", amount: 120_000 },
      { id: "i2", description: "Feeding", amount: 45_000 },
      { id: "i3", description: "Facilitator honorarium", amount: 15_000 },
    ],
    attachments: [{ id: "a1", name: "retreat_programme.pdf", size: "640 KB", kind: "proposal" }],
    comments: [
      {
        id: "c1",
        author: "Pastor Emmanuel Bassey",
        role: "National Youth Pastor",
        date: "2026-09-05",
        body: "Approved. Please keep receipts for the facilitator honorarium.",
      },
    ],
    activity: [
      { id: "e1", date: "2026-08-18", actor: "You", action: "Submitted for review" },
      { id: "e2", date: "2026-08-22", actor: "Pastor Grace Ojo", action: "Recommended" },
      { id: "e3", date: "2026-09-05", actor: "Pastor Emmanuel Bassey", action: "Approved" },
      { id: "e4", date: "2026-09-06", actor: "Finance", action: "Received for disbursement" },
    ],
    status: "with_finance",
    stageDates: {
      submitted: "2026-08-18",
      recommended: "2026-08-22",
      approval: "2026-09-05",
    },
    submittedAt: "2026-08-18",
    createdAt: "2026-08-16",
  },
  {
    id: "req-0834",
    reference: "REQ-2026-0834",
    programme: "Fellowship Outing Supplies",
    programmeDate: "2026-09-27",
    location: "Jabi Lake Park, Abuja",
    department: "Youth & Young Adults",
    purpose: "Refreshments and games equipment for the quarterly young adults fellowship outing.",
    requester: REQUESTERS.david,
    items: [
      { id: "i1", description: "Refreshments", amount: 45_000 },
      { id: "i2", description: "Transport (2 coaster buses)", amount: 40_000 },
    ],
    attachments: [],
    comments: [
      {
        id: "c1",
        author: "Pastor Grace Ojo",
        role: "Assistant National Youth Pastor",
        date: "2026-09-06",
        body: "The event budget looks solid, but we need more clarity on the venue and transport lines before this can go to the National Youth Pastor.",
        requestedChanges: [
          "Break down the transport cost line item — clarify if it includes fuel or is a flat charter.",
          "Attach a second-vendor quotation for the games equipment.",
          "Confirm the expected delegate count with the unit heads.",
        ],
      },
    ],
    activity: [
      { id: "e1", date: "2026-09-04", actor: "You", action: "Submitted for review" },
      { id: "e2", date: "2026-09-06", actor: "Pastor Grace Ojo", action: "Requested changes" },
    ],
    status: "changes_requested",
    stageDates: { submitted: "2026-09-04" },
    submittedAt: "2026-09-04",
    createdAt: "2026-09-03",
  },
  {
    id: "req-0828",
    reference: "REQ-2026-0828",
    programme: "Sound Equipment Upgrade",
    programmeDate: "2026-09-20",
    location: "Youth Chapel, Lagos",
    department: "Youth & Young Adults",
    purpose: "Replacement of two failing monitor speakers in the youth chapel.",
    requester: REQUESTERS.david,
    items: [{ id: "i1", description: "Stage monitors (2 units)", amount: 120_000 }],
    attachments: [],
    comments: [],
    activity: [{ id: "e1", date: "2026-09-07", actor: "You", action: "Created draft" }],
    status: "draft",
    stageDates: {},
    createdAt: "2026-09-07",
  },
  {
    id: "req-0821",
    reference: "REQ-2026-0821",
    programme: "Campus Outreach — Nsukka",
    programmeDate: "2026-08-15",
    location: "University of Nigeria, Nsukka",
    department: "Youth & Young Adults",
    purpose: "Two-day campus outreach with the student fellowship chapter.",
    requester: REQUESTERS.david,
    items: [
      { id: "i1", description: "Publicity materials", amount: 35_000 },
      { id: "i2", description: "Transport", amount: 55_000 },
      { id: "i3", description: "Refreshments", amount: 30_000 },
    ],
    attachments: [
      { id: "a1", name: "outreach_report.pdf", size: "1.1 MB", kind: "proposal" },
      { id: "a2", name: "disbursement_advice.pdf", size: "220 KB", kind: "other" },
    ],
    comments: [],
    activity: [
      { id: "e1", date: "2026-07-20", actor: "You", action: "Submitted for review" },
      { id: "e2", date: "2026-07-24", actor: "Pastor Grace Ojo", action: "Recommended" },
      { id: "e3", date: "2026-07-30", actor: "Pastor Emmanuel Bassey", action: "Approved" },
      { id: "e4", date: "2026-08-05", actor: "Finance", action: "Payment scheduled" },
      { id: "e5", date: "2026-08-08", actor: "Finance", action: "Disbursed" },
    ],
    status: "disbursed",
    stageDates: {
      submitted: "2026-07-20",
      recommended: "2026-07-24",
      approval: "2026-07-30",
      disbursement: "2026-08-08",
    },
    submittedAt: "2026-07-20",
    createdAt: "2026-07-18",
  },
  {
    id: "req-0815",
    reference: "REQ-2026-0815",
    programme: "Media Team Laptops",
    programmeDate: "2026-09-30",
    location: "Youth Secretariat, Abuja",
    department: "Youth & Young Adults",
    purpose: "Two editing laptops for the youth media team.",
    requester: REQUESTERS.david,
    items: [{ id: "i1", description: "Editing laptops (2 units)", amount: 250_000 }],
    attachments: [],
    comments: [
      {
        id: "c1",
        author: "Pastor Emmanuel Bassey",
        role: "National Youth Pastor",
        date: "2026-08-30",
        body: "Capital equipment sits outside the programme budget line this quarter. Please route this through the annual asset plan instead.",
      },
    ],
    activity: [
      { id: "e1", date: "2026-08-24", actor: "You", action: "Submitted for review" },
      { id: "e2", date: "2026-08-30", actor: "Pastor Emmanuel Bassey", action: "Rejected" },
    ],
    status: "rejected",
    stageDates: { submitted: "2026-08-24" },
    submittedAt: "2026-08-24",
    createdAt: "2026-08-23",
  },
  {
    id: "req-0806",
    reference: "REQ-2026-0806",
    programme: "Easter Youth Rally",
    programmeDate: "2026-04-05",
    location: "Provincial HQ, Ibadan",
    department: "Youth & Young Adults",
    purpose: "Easter weekend rally for the provincial youth chapters.",
    requester: REQUESTERS.david,
    items: [
      { id: "i1", description: "PA system hire", amount: 90_000 },
      { id: "i2", description: "Refreshments", amount: 60_000 },
      { id: "i3", description: "Transport", amount: 50_000 },
    ],
    attachments: [{ id: "a1", name: "rally_proposal.pdf", size: "720 KB", kind: "proposal" }],
    comments: [],
    activity: [
      { id: "e1", date: "2026-03-10", actor: "You", action: "Submitted for review" },
      { id: "e2", date: "2026-03-13", actor: "Pastor Grace Ojo", action: "Recommended" },
      { id: "e3", date: "2026-03-18", actor: "Pastor Emmanuel Bassey", action: "Approved" },
      { id: "e4", date: "2026-03-22", actor: "Finance", action: "Payment scheduled" },
      { id: "e5", date: "2026-03-25", actor: "Finance", action: "Disbursed" },
      { id: "e6", date: "2026-04-14", actor: "You", action: "Filed reconciliation" },
      { id: "e7", date: "2026-04-18", actor: "Finance", action: "Reconciliation accepted" },
    ],
    status: "reconciled",
    stageDates: {
      submitted: "2026-03-10",
      recommended: "2026-03-13",
      approval: "2026-03-18",
      disbursement: "2026-03-25",
      reconciled: "2026-04-18",
    },
    reconciliation: {
      // Came in under budget on transport; the balance went back to Finance.
      actuals: { i1: 90_000, i2: 62_500, i3: 34_000 },
      receipts: [
        { id: "r1", name: "pa_hire_receipt.pdf", size: "410 KB", kind: "receipt" },
        { id: "r2", name: "catering_invoice.jpg", size: "1.4 MB", kind: "receipt" },
        { id: "r3", name: "transport_receipts.pdf", size: "680 KB", kind: "receipt" },
      ],
      note: "Refreshments ran slightly over after the attendance rose to 520. Transport came in under because two chapters travelled in their own buses. Balance returned to Finance on 16 April.",
      submittedAt: "2026-04-14",
    },
    submittedAt: "2026-03-10",
    createdAt: "2026-03-08",
  },
  {
    id: "req-0851",
    reference: "REQ-2026-0851",
    programme: "Teens Bible Quiz Finals",
    programmeDate: "2026-10-11",
    location: "Provincial HQ, Ibadan",
    department: "Youth & Young Adults",
    purpose: "Prizes, refreshments and adjudication for the provincial teens quiz finals.",
    requester: REQUESTERS.david,
    items: [
      { id: "i1", description: "Prizes & trophies", amount: 48_000 },
      { id: "i2", description: "Refreshments", amount: 22_000 },
    ],
    attachments: [{ id: "a1", name: "quiz_budget.pdf", size: "310 KB", kind: "quotation" }],
    comments: [],
    activity: [{ id: "e1", date: "2026-09-06", actor: "You", action: "Submitted for review" }],
    status: "under_review",
    stageDates: { submitted: "2026-09-06" },
    submittedAt: "2026-09-06",
    createdAt: "2026-09-05",
  },
  {
    id: "req-0853",
    reference: "REQ-2026-0853",
    programme: "Lagos Teens Camp",
    programmeDate: "2026-10-24",
    location: "Badagry Camp Ground, Lagos",
    department: "Youth & Young Adults",
    purpose: "Four-day residential camp for 300 teenagers drawn from the eighteen Lagos chapters.",
    requester: REQUESTERS.ruth,
    items: [
      { id: "i1", description: "Camp ground hire (4 nights)", amount: 320_000 },
      { id: "i2", description: "Feeding (300 pax)", amount: 480_000 },
      { id: "i3", description: "Transport", amount: 150_000 },
      { id: "i4", description: "Camp materials & branding", amount: 90_000 },
    ],
    attachments: [
      { id: "a1", name: "camp_proposal.pdf", size: "2.1 MB", kind: "proposal" },
      { id: "a2", name: "campground_quotation.pdf", size: "540 KB", kind: "quotation" },
    ],
    comments: [],
    activity: [
      {
        id: "e1",
        date: "2026-09-05",
        actor: "Pastor Ruth Nwankwo",
        action: "Submitted for review",
      },
    ],
    status: "under_review",
    stageDates: { submitted: "2026-09-05" },
    submittedAt: "2026-09-05",
    createdAt: "2026-09-03",
  },
  {
    id: "req-0854",
    reference: "REQ-2026-0854",
    programme: "Eastern Zone Worship Night",
    programmeDate: "2026-09-26",
    location: "Cathedral Grounds, Enugu",
    department: "Youth & Young Adults",
    purpose: "Quarterly zonal worship night for the eastern chapters.",
    requester: REQUESTERS.samuel,
    items: [
      { id: "i1", description: "Sound & lighting", amount: 140_000 },
      { id: "i2", description: "Guest minister honorarium", amount: 100_000 },
      { id: "i3", description: "Security & stewards", amount: 45_000 },
    ],
    attachments: [{ id: "a1", name: "worship_night_plan.pdf", size: "880 KB", kind: "proposal" }],
    comments: [],
    activity: [
      {
        id: "e1",
        date: "2026-09-07",
        actor: "Pastor Samuel Okafor",
        action: "Submitted for review",
      },
    ],
    status: "under_review",
    stageDates: { submitted: "2026-09-07" },
    submittedAt: "2026-09-07",
    createdAt: "2026-09-06",
  },
  {
    id: "req-0855",
    reference: "REQ-2026-0855",
    programme: "Northern Outreach Materials",
    programmeDate: "2026-09-19",
    location: "Kaduna & Zaria chapters",
    department: "Youth & Young Adults",
    purpose:
      "Printing of Hausa-language outreach tracts and follow-up cards for the northern chapters.",
    requester: REQUESTERS.halima,
    items: [
      { id: "i1", description: "Tract printing (10,000 copies)", amount: 180_000 },
      { id: "i2", description: "Follow-up cards", amount: 35_000 },
    ],
    attachments: [{ id: "a1", name: "printer_quotation.pdf", size: "310 KB", kind: "quotation" }],
    comments: [],
    activity: [
      {
        id: "e1",
        date: "2026-08-30",
        actor: "Pastor Halima Bello",
        action: "Submitted for review",
      },
    ],
    status: "under_review",
    stageDates: { submitted: "2026-08-30" },
    submittedAt: "2026-08-30",
    createdAt: "2026-08-29",
  },
  {
    id: "req-0842",
    reference: "REQ-2026-0842",
    programme: "National Youth Choir Robes",
    programmeDate: "2026-11-01",
    location: "National Secretariat, Abuja",
    department: "Youth & Young Adults",
    purpose: "Replacement robes for the eighty-voice national youth choir ahead of the convention.",
    requester: REQUESTERS.ruth,
    items: [
      { id: "i1", description: "Robes (80 sets)", amount: 640_000 },
      { id: "i2", description: "Tailoring & alterations", amount: 95_000 },
    ],
    attachments: [
      { id: "a1", name: "robe_quotation_a.pdf", size: "480 KB", kind: "quotation" },
      { id: "a2", name: "robe_quotation_b.pdf", size: "515 KB", kind: "quotation" },
    ],
    comments: [
      {
        id: "c1",
        author: "Pastor Grace Ojo",
        role: "Assistant National Youth Pastor",
        date: "2026-09-04",
        body: "Two quotations attached and the lower one was taken. Recommending.",
      },
    ],
    activity: [
      {
        id: "e1",
        date: "2026-08-31",
        actor: "Pastor Ruth Nwankwo",
        action: "Submitted for review",
      },
      { id: "e2", date: "2026-09-04", actor: "Pastor Grace Ojo", action: "Recommended" },
    ],
    status: "awaiting_approval",
    stageDates: { submitted: "2026-08-31", recommended: "2026-09-04" },
    submittedAt: "2026-08-31",
    createdAt: "2026-08-30",
  },
  {
    id: "req-0845",
    reference: "REQ-2026-0845",
    programme: "Eastern Zone Discipleship Manuals",
    programmeDate: "2026-10-08",
    location: "Enugu",
    department: "Youth & Young Adults",
    purpose: "Printing of the revised discipleship manual for the eastern chapters.",
    requester: REQUESTERS.samuel,
    items: [{ id: "i1", description: "Manual printing (2,000 copies)", amount: 310_000 }],
    attachments: [{ id: "a1", name: "manual_quotation.pdf", size: "290 KB", kind: "quotation" }],
    comments: [
      {
        id: "c1",
        author: "Pastor Grace Ojo",
        role: "Assistant National Youth Pastor",
        date: "2026-09-06",
        body: "Unit cost is in line with last year's run. Recommending.",
      },
    ],
    activity: [
      {
        id: "e1",
        date: "2026-09-02",
        actor: "Pastor Samuel Okafor",
        action: "Submitted for review",
      },
      { id: "e2", date: "2026-09-06", actor: "Pastor Grace Ojo", action: "Recommended" },
    ],
    status: "awaiting_approval",
    stageDates: { submitted: "2026-09-02", recommended: "2026-09-06" },
    submittedAt: "2026-09-02",
    createdAt: "2026-09-01",
  },
  {
    id: "req-0838",
    reference: "REQ-2026-0838",
    programme: "Provincial Teachers' Seminar",
    programmeDate: "2026-10-17",
    location: "Provincial HQ, Ibadan",
    department: "Youth & Young Adults",
    purpose: "Two-day training for the province's Sunday school teachers.",
    requester: REQUESTERS.samuel,
    items: [
      { id: "i1", description: "Facilitator honorarium", amount: 120_000 },
      { id: "i2", description: "Training materials", amount: 65_000 },
    ],
    attachments: [{ id: "a1", name: "seminar_outline.pdf", size: "420 KB", kind: "proposal" }],
    comments: [
      {
        id: "c1",
        author: "Pastor Emmanuel Bassey",
        role: "National Youth Pastor",
        date: "2026-09-06",
        body: "Approved. Passing to Finance for disbursement.",
      },
    ],
    activity: [
      { id: "e1", date: "2026-08-27", actor: "Pastor Samuel Okafor", action: "Submitted for review" },
      { id: "e2", date: "2026-08-30", actor: "Pastor Grace Ojo", action: "Recommended" },
      { id: "e3", date: "2026-09-06", actor: "Pastor Emmanuel Bassey", action: "Approved" },
    ],
    status: "approved",
    stageDates: { submitted: "2026-08-27", recommended: "2026-08-30", approval: "2026-09-06" },
    submittedAt: "2026-08-27",
    createdAt: "2026-08-26",
  },
]
