import type { Requisition } from "./types"

export const CURRENT_USER = {
  name: "Pastor David Adeyemi",
  shortName: "Pastor David",
  role: "Head of Department",
  department: "Youth & Young Adults",
  unit: "Central Province",
  reviewer: "Pastor Grace Ojo",
  reviewerRole: "Assistant National Youth Pastor",
  approver: "Pastor Emmanuel Bassey",
  approverRole: "National Youth Pastor",
  initials: "DA",
}

export const SEED_REQUISITIONS: Requisition[] = [
  {
    id: "req-0847",
    reference: "REQ-2026-0847",
    programme: "Youth Convention 2026",
    programmeDate: "2026-11-15",
    location: "National Auditorium, Abuja",
    department: "Youth & Young Adults",
    purpose:
      "Annual youth leadership development convention for 1,200 delegates drawn from all twelve provinces. Covers venue, delegate transport and programme materials.",
    items: [
      { id: "i1", description: "Venue rental & setup", amount: 60_000 },
      { id: "i2", description: "Graphics & publicity", amount: 20_000 },
      { id: "i3", description: "Transport & logistics", amount: 70_000 },
    ],
    attachments: [
      { id: "a1", name: "convention_proposal_v2.pdf", size: "1.2 MB", kind: "proposal" },
      { id: "a2", name: "venue_quotation_setup.pdf", size: "850 KB", kind: "quotation" },
    ],
    comments: [
      {
        id: "c1",
        author: "Pastor Grace Ojo",
        role: "Assistant National Youth Pastor",
        date: "2026-09-02",
        body: "Budget looks sound. Recommending to the National Youth Pastor for approval.",
      },
    ],
    activity: [
      { id: "e1", date: "2026-08-28", actor: "You", action: "Created requisition" },
      { id: "e2", date: "2026-08-29", actor: "You", action: "Submitted for review" },
      { id: "e3", date: "2026-09-02", actor: "Pastor Grace Ojo", action: "Recommended" },
    ],
    status: "awaiting_approval",
    stageDates: { submitted: "2026-08-29", recommended: "2026-09-02" },
    submittedAt: "2026-08-29",
    createdAt: "2026-08-28",
  },
  {
    id: "req-0839",
    reference: "REQ-2026-0839",
    programme: "Leadership Retreat",
    programmeDate: "2026-10-03",
    location: "Ilesa Retreat Centre, Osun",
    department: "Youth & Young Adults",
    purpose:
      "Three-day residential retreat for forty unit leaders, focused on discipleship and succession planning.",
    items: [
      { id: "i1", description: "Accommodation (40 pax, 2 nights)", amount: 120_000 },
      { id: "i2", description: "Feeding", amount: 45_000 },
      { id: "i3", description: "Facilitator honorarium", amount: 15_000 },
    ],
    attachments: [
      { id: "a1", name: "retreat_programme.pdf", size: "640 KB", kind: "proposal" },
    ],
    comments: [
      {
        id: "c1",
        author: "Pastor Emmanuel Bassey",
        role: "National Youth Pastor",
        date: "2026-09-05",
        body: "Approved. Please keep receipts for the facilitator honorarium.",
      },
    ],
    activity: [
      { id: "e1", date: "2026-08-18", actor: "You", action: "Submitted for review" },
      { id: "e2", date: "2026-08-22", actor: "Pastor Grace Ojo", action: "Recommended" },
      { id: "e3", date: "2026-09-05", actor: "Pastor Emmanuel Bassey", action: "Approved" },
      { id: "e4", date: "2026-09-06", actor: "Finance Team", action: "Received for verification" },
    ],
    status: "with_finance",
    stageDates: {
      submitted: "2026-08-18",
      recommended: "2026-08-22",
      approval: "2026-09-05",
    },
    submittedAt: "2026-08-18",
    createdAt: "2026-08-16",
  },
  {
    id: "req-0834",
    reference: "REQ-2026-0834",
    programme: "Fellowship Outing Supplies",
    programmeDate: "2026-09-27",
    location: "Jabi Lake Park, Abuja",
    department: "Youth & Young Adults",
    purpose:
      "Refreshments and games equipment for the quarterly young adults fellowship outing.",
    items: [
      { id: "i1", description: "Refreshments", amount: 45_000 },
      { id: "i2", description: "Transport (2 coaster buses)", amount: 40_000 },
    ],
    attachments: [],
    comments: [
      {
        id: "c1",
        author: "Pastor Grace Ojo",
        role: "Assistant National Youth Pastor",
        date: "2026-09-06",
        body: "The event budget looks solid, but we need more clarity on the venue and transport lines before this can go to the National Youth Pastor.",
        requestedChanges: [
          "Break down the transport cost line item — clarify if it includes fuel or is a flat charter.",
          "Attach a second-vendor quotation for the games equipment.",
          "Confirm the expected delegate count with the unit heads.",
        ],
      },
    ],
    activity: [
      { id: "e1", date: "2026-09-04", actor: "You", action: "Submitted for review" },
      { id: "e2", date: "2026-09-06", actor: "Pastor Grace Ojo", action: "Requested changes" },
    ],
    status: "changes_requested",
    stageDates: { submitted: "2026-09-04" },
    submittedAt: "2026-09-04",
    createdAt: "2026-09-03",
  },
  {
    id: "req-0828",
    reference: "REQ-2026-0828",
    programme: "Sound Equipment Upgrade",
    programmeDate: "2026-09-20",
    location: "Youth Chapel, Lagos",
    department: "Youth & Young Adults",
    purpose: "Replacement of two failing monitor speakers in the youth chapel.",
    items: [
      { id: "i1", description: "Stage monitors (2 units)", amount: 120_000 },
    ],
    attachments: [],
    comments: [],
    activity: [{ id: "e1", date: "2026-09-07", actor: "You", action: "Created draft" }],
    status: "draft",
    stageDates: {},
    createdAt: "2026-09-07",
  },
  {
    id: "req-0821",
    reference: "REQ-2026-0821",
    programme: "Campus Outreach — Nsukka",
    programmeDate: "2026-08-15",
    location: "University of Nigeria, Nsukka",
    department: "Youth & Young Adults",
    purpose: "Two-day campus outreach with the student fellowship chapter.",
    items: [
      { id: "i1", description: "Publicity materials", amount: 35_000 },
      { id: "i2", description: "Transport", amount: 55_000 },
      { id: "i3", description: "Refreshments", amount: 30_000 },
    ],
    attachments: [
      { id: "a1", name: "outreach_report.pdf", size: "1.1 MB", kind: "proposal" },
      { id: "a2", name: "disbursement_advice.pdf", size: "220 KB", kind: "other" },
    ],
    comments: [],
    activity: [
      { id: "e1", date: "2026-07-20", actor: "You", action: "Submitted for review" },
      { id: "e2", date: "2026-07-24", actor: "Pastor Grace Ojo", action: "Recommended" },
      { id: "e3", date: "2026-07-30", actor: "Pastor Emmanuel Bassey", action: "Approved" },
      { id: "e4", date: "2026-08-05", actor: "Finance Team", action: "Verified" },
      { id: "e5", date: "2026-08-08", actor: "Treasury", action: "Disbursed" },
    ],
    status: "disbursed",
    stageDates: {
      submitted: "2026-07-20",
      recommended: "2026-07-24",
      approval: "2026-07-30",
      finance: "2026-08-05",
      disbursed: "2026-08-08",
    },
    submittedAt: "2026-07-20",
    createdAt: "2026-07-18",
  },
  {
    id: "req-0815",
    reference: "REQ-2026-0815",
    programme: "Media Team Laptops",
    programmeDate: "2026-09-30",
    location: "Youth Secretariat, Abuja",
    department: "Youth & Young Adults",
    purpose: "Two editing laptops for the youth media team.",
    items: [{ id: "i1", description: "Editing laptops (2 units)", amount: 250_000 }],
    attachments: [],
    comments: [
      {
        id: "c1",
        author: "Pastor Emmanuel Bassey",
        role: "National Youth Pastor",
        date: "2026-08-30",
        body: "Capital equipment sits outside the programme budget line this quarter. Please route this through the annual asset plan instead.",
      },
    ],
    activity: [
      { id: "e1", date: "2026-08-24", actor: "You", action: "Submitted for review" },
      { id: "e2", date: "2026-08-30", actor: "Pastor Emmanuel Bassey", action: "Rejected" },
    ],
    status: "rejected",
    stageDates: { submitted: "2026-08-24" },
    submittedAt: "2026-08-24",
    createdAt: "2026-08-23",
  },
  {
    id: "req-0851",
    reference: "REQ-2026-0851",
    programme: "Teens Bible Quiz Finals",
    programmeDate: "2026-10-11",
    location: "Provincial HQ, Ibadan",
    department: "Youth & Young Adults",
    purpose: "Prizes, refreshments and adjudication for the provincial teens quiz finals.",
    items: [
      { id: "i1", description: "Prizes & trophies", amount: 48_000 },
      { id: "i2", description: "Refreshments", amount: 22_000 },
    ],
    attachments: [{ id: "a1", name: "quiz_budget.pdf", size: "310 KB", kind: "quotation" }],
    comments: [],
    activity: [{ id: "e1", date: "2026-09-06", actor: "You", action: "Submitted for review" }],
    status: "under_review",
    stageDates: { submitted: "2026-09-06" },
    submittedAt: "2026-09-06",
    createdAt: "2026-09-05",
  },
]
